(add-to-list 'load-path "~/.emacs.d/elpa")
(add-to-list 'package-pinned-packages '(cider . "melpa-stable") t)
(require 'clojure-mode)
(add-hook 'clojure-mode-hook (lambda ()
			       (paredit-mode +1)
			       (auto-complete-mode +1)))
(add-to-list 'auto-mode-alist '("\\.cljs$" . clojure-mode))
(require 'paredit)
(define-key paredit-mode-map (kbd "C-M-a") 'backward-up-list)
(define-key paredit-mode-map (kbd "C-M-e") 'up-list)
(require 'ac-cider)
(add-hook 'cider-mode-hook 'ac-flyspell-workaround)
(add-hook 'cider-mode-hook 'ac-cider-setup)
(add-hook 'cider-repl-mode-hook 'ac-cider-setup)
(eval-after-load "auto-complete"
  '(add-to-list 'ac-modes 'cider-mode))
(provide 'dj)
